config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :organization_profiles, only: [:new, :create]

  root 'dashboard#show'

  resources :customers, only: [:index, :new, :create, :show] do
    resources :invoices do
      resources :payments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer, optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :contacts
  has_many :invoices

  accepts_nested_attributes_for :contacts

  validates :name, presence: true, uniqueness: {scope: :user}
  validates_associated :contacts

  def total_billed
    self.invoices.inject(0.0) do |sum, invoice|
      invoice.amount_due + sum
    end
  end

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :line_items
  has_many :payments

  validates :due_date, presence: true
  validates :terms, presence: true
  validates_associated :line_items

  accepts_nested_attributes_for :line_items

  enum status: {paid: 1, unpaid: 2, partially_paid: 3}
  enum terms: {due_on_receipt: 1, net_7: 2, net_15: 3, net_30: 4, net_45: 5, end_of_month: 6}

  def amount_due
    self.line_items.inject(0.0) do |sum, line_item|
      line_item.total + sum
    end
  end

  def total_paid
    self.payments.inject(0.0) do |total_paid, payment|
      payment.amount + total_paid
    end
  end

  def paid_in_full?
    total_paid >= amount_due
  end

  def partially_paid?
    total_paid > 0 && !paid_in_full?
  end

  def update_status
    if paid_in_full?
      self.status = :paid
    elsif partially_paid?
      self.status = :partially_paid
    else
      self.status = :unpaid
    end
    self.save
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice, optional: true

  def total
    self.quantity * self.rate
  end
end

app/models/organization_profile.rb
class OrganizationProfile < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice

  validates :amount, presence: true
  validates :date, presence: true
  validates :payment_method, presence: true

  enum payment_method: {cash: 0, credit_card: 1, debit_card: 2, check: 3, wire_transfer: 4, other: 5}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :organization_profile
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!

end

app/controllers/customers_controller.rb
class CustomersController < BaseController
  def index
    @customers = CustomerDecorator.decorate_collection(current_user.customers)
  end

  def new
    @customer = current_user.customers.new
    @customer.contacts.new
  end

  def create
    @customer = current_user.customers.new(customer_params)
    if @customer.save
      flash[:success] = "You have successfully added #{@customer.name}"
      redirect_to customers_path
    else
      render :new
    end
  end

  def show
    @customer = CustomerDecorator.decorate(current_customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :address, :phone_number, :website_url,
      contacts_attributes: [:first_name, :last_name, :email, :title, :phone_number])
  end

  def current_customer
    current_user.customers.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController
  def show
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < BaseController
  before_action :ensure_organization_profile_exists

  def new
    @invoice = current_customer.invoices.new
    @invoice.line_items.new
  end

  def create
    @invoice = current_customer.invoices.new(invoice_parameters)
    if @invoice.save
      flash[:success] = 'Your invoice was created successfully.'
      redirect_to customer_path(@invoice.customer.id)
    else
      render :new
    end
  end

  def show
    @invoice = InvoiceDecorator.decorate(current_invoice)
  end

  def edit
    @invoice = current_invoice
  end

  def update
    @invoice = current_invoice
    if @invoice.update_attributes(invoice_parameters)
      flash[:success] = 'Your invoice has been successfully updated.'
      redirect_to customer_path(current_customer)
    else
      render :edit
    end
  end


  private

  def invoice_parameters
    params.require(:invoice).permit(:invoice_date, :due_date, :terms, :notes, :adjustment_percentage,
      line_items_attributes: [:name, :description, :quantity, :rate, :id])
  end

  def current_customer
    current_user.customers.find(params[:customer_id])
  end

  def current_invoice
    current_customer.invoices.find(params[:id])
  end

  def ensure_organization_profile_exists
    unless current_user.organization_profile
      redirect_to new_organization_profile_path
    end
  end
end

app/controllers/organization_profiles_controller.rb
class OrganizationProfilesController < BaseController
  def new
    @profile = current_user.build_organization_profile
  end

  def create
    @profile = current_user.build_organization_profile(profile_params)
    if @profile.save
      redirect_to customers_path
    else
      render :new
    end
  end

  private

  def profile_params
    params.require(:organization_profile).permit(:name, :address, :phone_number, :website_url)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < BaseController
  def new
    @payment = PaymentDecorator.decorate(current_invoice.payments.new)
  end

  def create
    @nps = NewPaymentService.new(user: current_user, params: params)
    if @nps.call
      flash[:success] = 'Your payment has beeen successfully applied!'
      redirect_to customer_invoice_path(customer_id: params[:customer_id], id: params[:invoice_id])
    else
      render :new
    end
  end

  private

  def current_customer
    current_user.customers.find_by_id(params[:customer_id])
  end

  def current_invoice
    current_customer.invoices.find_by_id(params[:invoice_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
             concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
             concat message
           end)
    end
    nil
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render("forms/#{association.to_s.singularize}_fields", f: builder)
    end
    link_to(name, '#', class: 'add-nested-attribute-fields', data: {id: id, fields: fields.gsub("\n", '')})
  end

  def enum_for_select(class_enum)
    class_enum.map { |key, value| [key.humanize, key] }
  end
end

app/views/customers/_invoice_row.html.slim
- @customer.invoices.each do |invoice|
  tr.customer-invoice-row
    td = invoice.invoice_date_or_default
    td = invoice.due_date_or_default
    td = number_to_currency(invoice.amount_due)
    td 
      = link_to 'View', customer_invoice_path(@customer.id, invoice.id), class: 'btn btn-default btn-xs btn-show-on-hover'
      = link_to 'Edit', edit_customer_invoice_path(@customer.id, invoice.id), class: 'btn btn-default btn-xs btn-show-on-hover'

app/views/customers/index.html.slim
== content_for :page_title
  h2 Customers
== content_for :page_title_right
  = link_to 'New Customer', new_customer_path, class: 'btn btn-primary-inverse'

table.table.table-striped
  thead
    tr
      th
        strong Customer Name
      th
  tbody
    - @customers.each do |customer|
      tr
        td = customer.name
        td.text-right
          = link_to 'View Customer', customer, class: 'btn btn-default'
    
    
  

app/views/customers/new.html.slim
== content_for :page_title
  h2 New Customer

= bootstrap_form_for @customer do |f|
  = f.text_field :name
  = f.text_field :address
  = f.telephone_field :phone_number
  = f.url_field :website_url
  
  h4 Primary Contact
  = f.fields_for :contacts do |p|
    = p.text_field :first_name
    = p.text_field :last_name
    = p.telephone_field :phone_number
    = p.email_field :email
    = p.text_field :title
    
  = f.submit 'Create Customer'

app/views/customers/show.html.slim
== content_for :page_title
  h2 
    span.category Customers:
    = " #{@customer.name}"
== content_for :page_title_right
  .btn-group
    button.btn.btn-primary-inverse.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" 
      i.fa.fa-gear
    ul.dropdown-menu.dropdown-menu-right
      li = link_to 'Edit Customer', '#'
      li = link_to 'Delete Customer', '#'
  
.row
  .col-md-8
    .row
      .col-sm-9.col-xs-6
        h4 Invoices
      .col-sm-3.col-xs-6.text-right
        = link_to 'New Invoice', new_customer_invoice_path(@customer), class: 'btn btn-primary'
    .row-fluid
      table.table.table-striped
        thead
          tr
            th Invoice Date
            th Due Date
            th Total Amount
            th
        tbody
          - if @customer.invoices.any?
            = render partial: 'customers/invoice_row'
          - else
            tr
              td.warning.text-center colspan="3"
                | You have not created any invoices for #{@customer.name} yet.
  
  .col-md-4.border-box.text-center
    .big-num-container
      p total billed
      .big-num = number_to_currency(@customer.total_billed)

app/views/dashboard/show.html.slim
== content_for :page_title
  h2 Overview

app/views/forms/_line_item_fields.html.slim
fieldset.form-inline.nested-attributes.line-item-row
  = f.text_field :name, wrapper: {class: 'col-sm-6'}, placeholder: 'ex. Consulting'
  = f.number_field :quantity, class: 'quantity', wrapper: {class: 'col-sm-3'}, min: 0
  = f.number_field :rate, class: 'currency', wrapper: {class: 'col-sm-3'}

app/views/invoices/edit.html.slim
== content_for :page_title
  h2
    span.category = "Customers: #{@invoice.customer.name} / "
    span Edit Invoice

.row
  .col-sm-8
    = bootstrap_form_for(@invoice, url: customer_invoice_path(customer_id: @invoice.customer, id: @invoice)) do |f|
      h4 General
      = f.date_field :invoice_date, class: 'datepicker', wrapper: {class: 'col-sm-6'}
      = f.date_field :due_date, class: 'datepicker', wrapper: {class: 'col-sm-6'}
      = f.select :terms, enum_for_select(Invoice.terms), {}, layout: :default, wrapper: {class: 'col-sm-12'}
      = f.text_field :notes, layout: :default, wrapper: {class: 'col-sm-12'}, 
          help: 'These notes will be displayed to your customer at the bottom of the invoice.',
          placeholder: 'Thank you for your business!'
      .clearfix
      
      .line-items-section
        h4 Line Items
        = f.fields_for :line_items do |builder|
          = render partial: 'forms/line_item_fields', locals: {f: builder}
        
        = link_to_add_fields 'Add Line Item', f, :line_items
      
      = f.submit 'Update Invoice', class: 'btn btn-primary'
      = link_to 'Cancel', customer_path(@invoice.customer), class: 'btn btn-link'
      
  .col-sm-4.border-box.text-center
    .big-num-container
      p total invoice value
      .big-num#invoice-value-number $0.00

== content_for :page_footer
  javascript:
    $(document).on('turbolinks:load', function() {
      $('.datepicker').flatpickr({minDate: 'today', defaultDate: new Date(), altInput: true});
      $('input.currency').currencyInput();
      
      $(document).on('factura:line-item-added', function(e) {
        $(e.lineItem).find('.currency').currencyInput();
      });

      $('.line-items-section').invoiceTotaler({rebindOn: 'factura:line-item-added'});
    });

app/views/invoices/new.html.slim
== content_for :page_title
  h2
    span.category = "Customers: #{@invoice.customer.name} / "
    span New Invoice

.row
  .col-sm-8
    = bootstrap_form_for(@invoice, url: customer_invoices_path(@invoice.customer)) do |f|
      h4 General
      = f.date_field :invoice_date, class: 'datepicker', wrapper: {class: 'col-sm-6'}
      = f.date_field :due_date, class: 'datepicker', wrapper: {class: 'col-sm-6'}
      = f.select :terms, enum_for_select(Invoice.terms), {}, layout: :default, wrapper: {class: 'col-sm-12'}
      = f.text_field :notes, layout: :default, wrapper: {class: 'col-sm-12'}, 
          help: 'These notes will be displayed to your customer at the bottom of the invoice.',
          placeholder: 'Thank you for your business!'
      .clearfix
      
      .line-items-section
        h4 Line Items
        = f.fields_for :line_items do |builder|
          = render partial: 'forms/line_item_fields', locals: {f: builder}
          
        = link_to_add_fields 'Add Line Item', f, :line_items
      
      = f.submit 'Create Invoice', class: 'btn btn-primary'
      = link_to 'Cancel', customer_path(@invoice.customer), class: 'btn btn-link'
      
  .col-sm-4.border-box.text-center
    .big-num-container
      p total invoice value
      .big-num#invoice-value-number $0.00

== content_for :page_footer
  javascript:
    $(document).on('turbolinks:load', function() {
      $('.datepicker').flatpickr({minDate: 'today', defaultDate: new Date(), altInput: true});
      $('input.currency').currencyInput();
      
      $(document).on('factura:line-item-added', function(e) {
        $(e.lineItem).find('.currency').currencyInput();
      });

      $('.line-items-section').invoiceTotaler({rebindOn: 'factura:line-item-added'});
    });

app/views/invoices/pdf.html.slim
style
  = Rails.application.assets.find_asset('application.css').to_s.html_safe

.row
  .col-sm-8
    h2 General
    
    .row-fluid
      h6 Invoice Date
      p = invoice_date_or_default
    
    .row-fluid
      h6 Due Date
      p = due_date_or_default
    
    .row-fluid
      h6 Terms
      p = terms_or_default
    
    .row-fluid
      h6 Notes
      p = notes_or_default
      
    .line-items-section
      h2 Line Items
      - line_items.each do |line_item|
        .row-fluid
          .col-sm-6
            h6 Name
            p = line_item.name
          
          .col-sm-3
            h6 Quantity
            p = line_item.quantity
          
          .col-sm-3
            h6 Rate
            p = line_item.rate

  .col-sm-4.border-box.text-center
    .big-num-container
      p total invoice value
      .big-num#invoice-value-number = number_to_currency(amount_due)

app/views/invoices/show.html.slim
== content_for :page_title
  h2
    span.category = "Customer: #{@invoice.customer_name} / "
    span Invoice
== content_for :page_title_right
  = link_to 'Record Payment', 
    new_customer_invoice_payment_path(customer_id: @invoice.customer.id, invoice_id: @invoice.id), class: 'btn btn-primary-inverse'


.row
  .col-sm-8
    h2 General
    
    .row-fluid
      h6 Invoice Date
      p = @invoice.invoice_date_or_default
    
    .row-fluid
      h6 Due Date
      p = @invoice.due_date_or_default
    
    .row-fluid
      h6 Terms
      p = @invoice.terms_or_default
    
    .row-fluid
      h6 Notes
      p = @invoice.notes_or_default
      
    .line-items-section
      h2 Line Items
      - @invoice.line_items.each do |line_item|
        .row-fluid
          .col-sm-6
            h6 Name
            p = line_item.name
          
          .col-sm-3
            h6 Quantity
            p = line_item.quantity
          
          .col-sm-3
            h6 Rate
            p = line_item.rate

  .col-sm-4.border-box.text-center
    .big-num-container
      p total invoice value
      .big-num#invoice-value-number = number_to_currency(@invoice.amount_due)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Factura
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/css?family=Arvo:400,700|Open+Sans:300:700" rel="stylesheet"
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/2.3.4/flatpickr.min.css"
  body
    = render partial: 'shared/header'
    .container
      = flash_messages
      = yield

    script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/2.3.4/flatpickr.min.js"

    - if content_for? :page_footer
      = yield :page_footer

app/views/organization_profiles/new.html.slim
== content_for :page_title
  h2 Organization Profile

.row
  .col-sm-8.col-sm-offset-2.col-xs-12.col-xs-offset-0
    .row-fluid.text-center
      h3 We need some basic information from you! 
      p This information will be displayed in various places on your invoices.
    
    .spacer
    .row-fluid
      = bootstrap_form_for @profile do |f|
        = f.text_field :name, help: 'This will be the name shown on your invoice.'
        = f.text_field :address, help: 'This is the address which checks could be sent to.'
        = f.telephone_field :phone_number
        = f.url_field :website_url
        = f.submit 'Save Profile', class: 'btn btn-primary'

app/views/payments/new.html.slim
h1 Record Payment

= bootstrap_form_for @payment, url: @payment.create_path, method: :post do |f|
  = f.date_field :date, class: 'datepicker', label: 'Payment Date'
  = f.number_field :amount, class: 'currency'
  = f.select :payment_method, enum_for_select(Payment.payment_methods)
  = f.text_field :memo
  = f.submit 'Record Payment', class: 'btn btn-primary'


== content_for :page_footer
  javascript:
    $(document).on('turbolinks:load', function() {
      $('.datepicker').flatpickr({minDate: 'today', defaultDate: new Date(), altInput: true});
      $('input.currency').currencyInput();
    });

app/views/shared/_header.html.slim
- if current_user
  = render partial: 'shared/navbar'
  - if content_for? :page_title
    .row-fluid.page-title
      - if content_for? :page_title_right
        .col-sm-8.text-center-xs
          = yield :page_title
        .col-sm-4.text-right.text-center-xs
          = yield :page_title_right
      - else
        .col-sm-12.text-center-xs
          = yield :page_title
      .clearfix
  
  .sidebar-overlay
  .sidebar.closed
    .sidebar-nav
      .close-container
        i.sidebar-toggle-btn.fa.fa-close aria-hidden="true"
        
      ul.nav.nav-sidebar
        li
          = link_to 'Sign Out', destroy_user_session_path, method: :delete

app/views/shared/_navbar.html.slim
#top-nav.nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Factura', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Customers', customers_path
        li
          a href="#"  Open Invoices
        li
          a.sidebar-toggle-btn href="#"
            i.fa.fa-bars.sidebar-btn-toggle
            